# image
image: Visual Studio 2017

# build platform
platform: x64

# clone directory
clone_folder: c:\aeon-stak-amd

version: '1.0.{build}-{branch}'

install:
  - if not exist "c:\aeon-stak-dep" (mkdir c:\aeon-stak-dep & curl -sL https://github.com/fireice-uk/xmr-stak-dep/releases/download/v1/xmr-stak-dep.zip -o aeon-stak-dep.zip & 7z x aeon-stak-dep.zip -o"c:\aeon-stak-dep" -y)
  - if not exist "c:\xmr-stak-amd-dep-1.0" (curl -sL https://github.com/RafalSladek/xmr-stak-amd-dep/archive/v1.0.zip -o aeon-stak-amd-dep-1.0.zip  & 7z x aeon-stak-amd-dep-1.0.zip -o"C:\" -y)
  - set AMDAPPSDKROOT=C:\xmr-stak-amd-dep-1.0\3.0
cache:
    - c:\aeon-stak-dep
    - c:\xmr-stak-amd-dep-1.0
    
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
  - cd c:\aeon-stak-amd
  - mkdir build
  - cd build
  - set CMAKE_PREFIX_PATH=C:\aeon-stak-dep\hwloc;C:\aeon-stak-dep\libmicrohttpd;C:\aeon-stak-dep\openssl;
  - set CMAKE_CXX_FLAGS_STATIC=ON
  - cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
  - msbuild xmr-stak-amd.sln /p:Configuration=Release

test_script:
  - cd c:\aeon-stak-amd\build\bin\Release
  - copy ..\..\..\config.txt .
  - copy ..\..\..\ReadMe.txt .
  - copy c:\aeon-stak-dep\openssl\bin\*.* .
  - mkdir opencl
  - copy ..\..\..\opencl\*.* opencl\
  - ren xmr-stak-amd.exe aeon-stak-amd.exe
  - tree /f
artifacts:
  - path: build\bin\Release
    name: aeon-stak-amd-win
#  - aeon-stak-amd.exe